[package]
name = "isle-native"
version.workspace = true
edition.workspace = true

[dependencies]
isle-core = { path = "../isle-core" }
isle-ui = { path = "../isle-ui" }
windows = { version = "=0.52.0", features = [
 "Web_Http", "Web_Http_Headers", "Data_Json", "Storage_Streams", "Graphics_Imaging",
 "Media_Control", "Foundation", "Foundation_Collections", "Win32_System_WinRT",
 "implement", "Win32_UI_Accessibility", "Win32_UI_Controls", "Win32_System_Ole", "Win32_System_Variant",
 "Foundation_Numerics", "Win32_Foundation", "Win32_System_SystemInformation", "Win32_System_Com", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_Security",
 "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse",
 "Win32_Graphics_Gdi", "Win32_Graphics_Direct2D", "Win32_Graphics_Direct2D_Common",
 "Win32_Graphics_DirectWrite", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D11",
 "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_DirectComposition"
] }
